config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:show]
  root "list#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  paginates_per 30

  def full_name
    "#{first_name} '#{nickname}' #{last_name}".sub("'' ",'')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
    @contact = Contact.find(params[:id])
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def index
    @contacts = Contact.order(:last_name).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/contacts/show.html.erb
&laquo; <%= link_to "back", "javascript:history.back()" %>
<h1><%= @contact.full_name %></h1>

<dl class="contact-details dl-horizontal">
  <dt><%= t(:first_name) %></dt>
  <dd><%= @contact.first_name %></dd>

  <dt><%= t(:last_name) %></dt>
  <dd><%= @contact.last_name %></dd>

  <dt><%= t(:nickname) %></dt>
  <dd><%= @contact.nickname %></dd>

  <dt><%= t(:phones) %></dt>
  <dd>
    <ul>
      <% Array.wrap(@contact.phones).each do |phone|-%>
        <li><%= link_to phone, "tel:#{phone}" -%></li>
      <% end -%>
    </ul>
  </dd>

  <dt><%= t(:emails) %></dt>
  <dd>
    <ul>
      <% Array.wrap(@contact.emails).each do |email|-%>
        <li><%= link_to email -%></li>
      <% end -%>
    </ul>
  </dd>

  <dt><%= t(:social_links) %></dt>
  <dd>
    <ul>
      <% Array.wrap(@contact.social_links).each do |social_link|-%>
        <li><%= link_to social_link -%></li>
      <% end -%>
    </ul>
  </dd>

  <dt><%= t(:addresses) %></dt>
  <dd>
    <ul>
      <% Array.wrap(@contact.addresses).each do |address|-%>
        <li>
          <div><strong><%= address['street_name']+" "+address['street_number'].to_s %></strong></div>
          <div><%= address['postcode'].to_s+" "+address['city'] %></div>
          <div><em><%= address['country'] %></em></div>
        </li>
      <% end -%>
    </ul>
  </dd>

  <dt><%= t(:notes) %></dt>
  <dd><%= @contact.notes %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressbookExampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/list/_contact.html.erb
<li>
  <%= link_to contact.full_name, contact_path(contact) %>
</li>

app/views/list/index.html.erb
<h1>Address Book</h1>

<ul class="contacts">
  <%= render partial: 'contact', collection: @contacts %>
</ul>

<%= paginate @contacts %>